name: API Continous Testing 

on:
  # push:
  # branches:
  #    - main
  # pull_request:
  # schedule:
  #  - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      run-tests:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Manually trigger the tests'
        required: true
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: inputs
      run: echo "Environment is ${{ inputs.environment }} and run-tests is ${{ inputs.run-tests }}"
    
    - name: list files
      run: ls -la
    
    - name: Checkout current repo
      uses: actions/checkout@v4
  
    - name: list files
      run: ls -la

    - name: Checkout remote workflow repo
      uses: actions/checkout@v4
      with:
        repository: basivireddy1212/python-pytest-api-testing
        ref: main
#        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # needed if repo is private

    - name: list files
      run: ls -la

      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Run tests and generate report
      run: |
        pytest -v tests/test_users.py --html=report.html
      working-directory: ${{ github.workspace }}

    - name: Save test report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
